create table files
(
    id     int primary key generated by default as identity,
    file_path varchar(255),
    name      varchar(255)

);
create table users
(
    id     int primary key generated by default as identity,
    name varchar(255)

);
create table events
(

    id     int primary key generated by default as identity ,
    file_id int,
    user_id int,
    foreign key (file_id)references files(id),
    foreign key (user_id)references users(id)

);